name: Races
main: xfury\races\MainClass
description: Choose your fate!
version: 1.0.1
author: [XFuryMCPE, GlacierShard92]
api: [1.13.0, 2.0.0]

commands:
 race:
  description: Choose your /race between bunny, miner or elf!
  permission: races.use

permissions:
 races.use:
  description: Permission for /race
  default: true
